apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: kube-eventer
  name: kube-eventer
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-eventer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "8084"
        prometheus.io/scrape: "true"
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        app: kube-eventer
    spec:
      containers:
        - command:
            - /kube-eventer
            - --source=kubernetes:https://kubernetes.default
            - --sink=elasticsearch:http://elasticsearch-logging:9200?sniff=false&ver=6
            - --sink=prometheus
          env:
            - name: TZ
              value: Asia/Shanghai
          image: harbor.ffcs.cn/library/kube-eventer-amd64:v1.2.0-6dac082
          imagePullPolicy: IfNotPresent
          name: kube-eventer
          resources:
            limits:
              cpu: 500m
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
            - mountPath: /usr/share/zoneinfo
              name: zoneinfo
              readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-eventer
      serviceAccountName: kube-eventer
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
        - hostPath:
            path: /usr/share/zoneinfo
            type: ""
          name: zoneinfo
